FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /adk-server ./cmd/adk-server

FROM gcr.io/distroless/base-debian12

WORKDIR /

COPY --from=builder /adk-server /adk-server

EXPOSE 9090

ENTRYPOINT ["/adk-server"]
